### ISSUE TITLE
compilation fails for the HEAD version !

### ISSUE THREAD

**Issue by tsarangi** [uwcms/FinalStateAnalysis#160]
I tried to compile using 5.3.3 and it fails with the following errors:
##### 

/afs/hep.wisc.edu/cms/tapas/FinalStateAnalysis_Package/2013-02-25-8TeV-53X-PatTuple_Master/src/DataFormats/PatCandidates/src/Muon.cc: In member function 'bool pat::Muon::isHighPtMuon(const reco::Vertex&, pat::Muon::TunePType) const':
/afs/hep.wisc.edu/cms/tapas/FinalStateAnalysis_Package/2013-02-25-8TeV-53X-PatTuple_Master/src/DataFormats/PatCandidates/src/Muon.cc:434:77: error: no matching function for call to 'tevOptimized(const pat::Muon&, int, double, double, double)'
/afs/hep.wisc.edu/cms/tapas/FinalStateAnalysis_Package/2013-02-25-8TeV-53X-PatTuple_Master/src/DataFormats/PatCandidates/src/Muon.cc:434:77: note: candidates are:
/cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_3/src/DataFormats/MuonReco/interface/MuonCocktails.h:20:33: note: reco::Muon::MuonTrackTypePair muon::tevOptimized(const TrackRef&, const TrackRef&, const TrackRef&, const TrackRef&, double, double, double)
/cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_3/src/DataFormats/MuonReco/interface/MuonCocktails.h:20:33: note:   no known conversion for argument 1 from 'const pat::Muon' to 'const TrackRef& {aka const edm::Refstd::vector<reco::Track >&}'
/cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_3/src/DataFormats/MuonReco/interface/MuonCocktails.h:30:40: note: reco::Muon::MuonTrackTypePair muon::tevOptimized(const reco::Muon&, double, double, double)
/cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_3/src/DataFormats/MuonReco/interface/MuonCocktails.h:30:40: note:   candidate expects 4 arguments, 5 provided
/cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_3/src/DataFormats/MuonReco/interface/MuonCocktails.h:53:40: note: reco::Muon::MuonTrackTypePair muon::tevOptimized(const TrackRef&, const TrackRef&, const TrackToTrackMap&, const TrackToTrackMap&, const TrackToTrackMap&, double, double, double)
/cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_3/src/DataFormats/MuonReco/interface/MuonCocktails.h:53:40: note:   no known conversion for argument 1 from 'const pat::Muon' to 'const TrackRef& {aka const edm::Refstd::vector<reco::Track >&}'
/cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_3/src/DataFormats/MuonReco/interface/MuonCocktails.h:70:40: note: reco::Muon::MuonTrackTypePair muon::tevOptimized(const reco::Muon&, const TrackToTrackMap&, const TrackToTrackMap&, const TrackToTrackMap&)
/cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_3/src/DataFormats/MuonReco/interface/MuonCocktails.h:70:40: note:   candidate expects 4 arguments, 5 provided
/afs/hep.wisc.edu/cms/tapas/FinalStateAnalysis_Package/2013-02-25-8TeV-53X-PatTuple_Master/src/DataFormats/PatCandidates/src/Muon.cc:446:73: error: no matching function for call to 'tevOptimized(const pat::Muon&, int, double, double, int)'
/afs/hep.wisc.edu/cms/tapas/FinalStateAnalysis_Package/2013-02-25-8TeV-53X-PatTuple_Master/src/DataFormats/PatCandidates/src/Muon.cc:446:73: note: candidates are:
/cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_3/src/DataFormats/MuonReco/interface/MuonCocktails.h:20:33: note: reco::Muon::MuonTrackTypePair muon::tevOptimized(const TrackRef&, const TrackRef&, const TrackRef&, const TrackRef&, double, double, double)
/cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_3/src/DataFormats/MuonReco/interface/MuonCocktails.h:20:33: note:   no known conversion for argument 1 from 'const pat::Muon' to 'const TrackRef& {aka const edm::Refstd::vector<reco::Track >&}'
/cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_3/src/DataFormats/MuonReco/interface/MuonCocktails.h:30:40: note: reco::Muon::MuonTrackTypePair muon::tevOptimized(const reco::Muon&, double, double, double)
/cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_3/src/DataFormats/MuonReco/interface/MuonCocktails.h:30:40: note:   candidate expects 4 arguments, 5 provided
/cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_3/src/DataFormats/MuonReco/interface/MuonCocktails.h:53:40: note: reco::Muon::MuonTrackTypePair muon::tevOptimized(const TrackRef&, const TrackRef&, const TrackToTrackMap&, const TrackToTrackMap&, const TrackToTrackMap&, double, double, double)
/cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_3/src/DataFormats/MuonReco/interface/MuonCocktails.h:53:40: note:   no known conversion for argument 1 from 'const pat::Muon' to 'const TrackRef& {aka const edm::Refstd::vector<reco::Track >&}'
/cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_3/src/DataFormats/MuonReco/interface/MuonCocktails.h:70:40: note: reco::Muon::MuonTrackTypePair muon::tevOptimized(const reco::Muon&, const TrackToTrackMap&, const TrackToTrackMap&, const TrackToTrackMap&)
/cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_3/src/DataFormats/MuonReco/interface/MuonCocktails.h:70:40: note:   candidate expects 4 arguments, 5 provided

> > Compiling  /afs/hep.wisc.edu/cms/tapas/FinalStateAnalysis_Package/2013-02-25-8TeV-53X-PatTuple_Master/src/DataFormats/PatCandidates/src/TauCaloSpecific.cc 
> > Compiling  /afs/hep.wisc.edu/cms/tapas/FinalStateAnalysis_Package/2013-02-25-8TeV-53X-PatTuple_Master/src/DataFormats/PatCandidates/src/TauJetCorrFactors.cc 
> > gmake: **\* [tmp/slc5_amd64_gcc462/src/DataFormats/PatCandidates/src/DataFormatsPatCandidates/Muon.o] Error 1
> > #####
